# Generated by Django 5.1.1 on 2024-09-22 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "department_ID",
                    models.CharField(
                        max_length=20, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("department_Name", models.CharField(max_length=50)),
                ("department_Floor", models.CharField(max_length=50)),
                ("department_Dean", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "program_ID",
                    models.CharField(
                        max_length=20, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("program_Name", models.CharField(max_length=50)),
                ("degree_Type", models.CharField(max_length=50)),
                (
                    "department_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="form.department",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "student_ID",
                    models.CharField(
                        max_length=20, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("student_FirstName", models.CharField(max_length=50)),
                ("student_LastName", models.CharField(max_length=50)),
                ("student_GPA", models.DecimalField(decimal_places=2, max_digits=3)),
                ("student_Age", models.IntegerField()),
                (
                    "student_ProgramID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="form.program"
                    ),
                ),
            ],
        ),
    ]
