# Generated by Django 5.1.1 on 2024-09-22 19:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("form", "0002_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="contact_Message",
            field=models.CharField(max_length=800),
        ),
    ]
