# Generated by Django 5.1.1 on 2024-09-22 20:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("form", "0003_alter_contact_contact_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="contact_Message",
            field=models.TextField(max_length=800),
        ),
    ]
